=== francisco-byte/TrabalhoIntegracaoSistemas/Servidor/shared/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": ["id", "name", "price", "stock"],
    "properties": {
      "id": { "type": "integer" },
      "name": { "type": "string" },
      "price": { "type": "number" },
      "stock": { "type": "integer" }
    }
  }

=== francisco-byte/TrabalhoIntegracaoSistemas/Servidor/shared/produtos.json
[
  {
    "id": 1,
    "name": "Teste",
    "price": 3.0,
    "stock": 4
  },
  {
    "id": 2,
    "name": "Teste",
    "price": 3.0,
    "stock": 4
  },
  {
    "id": 3,
    "name": "teste4",
    "price": 10.0,
    "stock": 9
  },
  {
    "id": 4,
    "name": "teste3",
    "price": 12.0,
    "stock": 8
  }
]
